.PHONY: clean All

All:
	@echo "==========Building project:[ integer_addition - Debug ]=========="
	@cd "integer_addition" && "$(MAKE)" -f  "integer_addition.mk"
clean:
	@echo "==========Cleaning project:[ integer_addition - Debug ]----------"
	@cd "integer_addition" && "$(MAKE)" -f  "integer_addition.mk" clean
